# Generated by Django 6.0.4 on 2026-04-23 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sac', '0002_lab05_admin_alignment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cita',
            options={'ordering': ['-fecha', 'hora_inicio'], 'verbose_name': 'Appointment', 'verbose_name_plural': 'Appointments'},
        ),
        migrations.AlterModelOptions(
            name='estilista',
            options={'verbose_name': 'Stylist', 'verbose_name_plural': 'Stylists'},
        ),
        migrations.AlterModelOptions(
            name='horarioestilista',
            options={'verbose_name': 'Stylist schedule', 'verbose_name_plural': 'Stylist schedules'},
        ),
        migrations.AlterModelOptions(
            name='peluqueria',
            options={'ordering': ['nombre'], 'verbose_name': 'Hair salon', 'verbose_name_plural': 'Hair salons'},
        ),
        migrations.AlterModelOptions(
            name='servicio',
            options={'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
